# Haskell Dockerfile Linter
# see https://github.com/hadolint/hadolint
ignored:
  - DL3008 # Pin versions in apt get install.
  - DL3013 # Pin versions in pip
  - DL3059 # info: Multiple consecutive `RUN` instructions.

trustedRegistries:
  - docker.io
  - mcr.microsoft.com
